### PR TITLE
fixes

### LINKED ISSUE #20: Error 500 (Strange ban with multibyte string in IP)
Send POST http://localhost:4346/api/bans
 JSON REQUEST BODY:
```
{
  "target": {
    "ip": "长款t恤女"
  },
  "reason": "Strange ban with multibyte string in IP",
  "ttl": 310
}
```
Response code: 500
 JSON RESPONSE BODY:
```
{
  "code": 500,
  "reason": "CF responded unsuccessfull: [\"failed to create filter: Filter parsing error (1:11):\\nip.src eq 长款t恤女\\n          ^^^^^^^^^^^^^ expected IP address character\\n\"])",
  "details": null
}
```

### LINKED ISSUE #21: Error 500 (Strange ban with empty IP)
Send POST http://localhost:4346/api/bans
 JSON REQUEST BODY:
```
{
  "target": {
    "ip": ""
  },
  "reason": "Strange ban with empty IP",
  "ttl": 301
}
```
Response code: 500
 JSON RESPONSE BODY:
```
{
  "code": 500,
  "reason": "CF responded unsuccessfull: [\"failed to create filter: Filter parsing error (1:10):\\nip.src eq\\n         ^ expected IP address character\\n\"])",
  "details": null
}
```

### LINKED ISSUE #24: Error 400 (Json deserialize error.....)
Send POST http://localhost:4346/api/bans
1.
 JSON REQUEST BODY
```
{
  "target": {
    "ip": "192.168.13.13",
    "user_agent": "test user agent"
  },
  "reason": "Test ban",
  "ttl": null
}
```
JSON RESPONSE BODY
```

"Json deserialize error: invalid type: null, expected u64 at line 1 column 94"
```
2.
 JSON REQUEST BODY
```
{
  "target": {
    "ip": "192.168.13.13",
    "user_agent": "test user agent"
  },
  "reason": null,
  "ttl": 300
}
```
 JSON RESPONSE BODY
```
"Json deserialize error: invalid type: null, expected a string at line 1 column 77"
```
3.
 JSON REQUEST BODY
```
{
  "target": {
    "ip": 192
  },
  "reason": "Test ban",
  "ttl": 300
}
```
 JSON RESPONSE BODY
```
"Json deserialize error: invalid type: integer `192`, expected a string at line 1 column 19"
```

### PR DESCRIPTION
**Pull request by citizensix**
Closes #18 
Closes #19 
Closes #20 
Closes #21  
Closes #22  
Closes #23  
Closes #24

### CODE REVIEW

**Review by stuffy-idler — CHANGES_REQUESTED** [review]

**Review by stuffy-idler — DISMISSED** [review]

**Comment by stuffy-idler** [comment]
@Rabid-Squirrel, please check, whether specified bugs were fixed.

**Comment by stuffy-idler** [comment]
@citizensix let's extend support of IP to IPv6. Please specify it in docs

**Comment by Rabid-Squirrel** [comment]
checked, work.

**Comment by stuffy-idler** [comment]
@citizensix PR can be merged

**Pull request merged**
